---
title: "Rally Animations"
author: "Pat Healy"
date: "23 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
longral_df <- read.csv(file="longral.csv")
seventythree_df <- read.csv(file="longest.csv")


```


#Top down court view
```{r }
#
library(plotly)
library(ggplot2)
library(tidyr)
library(dplyr)
library(tidyverse)
#--- Packages Required
# require(ggplot2)
# require(plotly)

#--- Outline of the court
court_trace <- data.frame(x = c(-11.89, -11.89, 0, 0, 0, 11.89, 11.89, -11.89, -11.89, 11.89, 11.89, -11.89, -6.4, -6.4, 6.4, 6.4, 6.4, -6.4),
                          y = c(5.49, -5.49, -5.49, 5.49, -5.49, -5.49, 5.49, 5.49, 4.115, 4.115, -4.115, -4.115, -4.115, 4.115, 4.115, -4.115, 0, 0),
                          z = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
net_trace <- data.frame(x = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                        y = c(-5.49,-5.49, -6.4, -6.4, -5.49, 0, 5.49, 6.4, 6.4, 5.49, 5.49),
                        z = c(1.07, 0, 0, 1.07, 1.07, 0.914, 1.07, 1.07, 0, 0, 1.07))
service_trace <- data.frame(x = c(-8, 0, 0, 0, -6.4, -6.4, 0, -6.4, -6.4, -6.4, -6.4, -6.4,  0, 0, -8),
                            y = c(-5.49, -5.49, -4.115, 4.115, 4.115, 0, 0, 0, -4.115, -5.49, 5.49, -4.115, -4.115, 5.49, 5.49),
                            z = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,0 ,0))
    
axis_labels <- data.frame(x.break = c(-21.89:-11.89, -6.4, 0, 6.4, 11.89),
                          x.label = c("-10m","","","","","-5m","","","","",
                                      "Baseline","Service Line","Net","Service Line","Baseline"),
                          y.break = c(-5.49,-4.115,0,4.115,5.49),
                          y.label = c("Doubles", "Singles","Centre","Singles","Doubles"),
                          z.break = c(0,0.992,2,3,4),
                          z.label = c("Ground", "Net", "2m", "3m", "4m"))
#--- Top down court view
court_topdown <- ggplot() + 
    labs(x = "x direction", y = "y direction") + 
    scale_x_continuous(breaks = axis_labels$x.break,
                       labels = axis_labels$x.label) +
    scale_y_continuous(breaks = axis_labels$y.break,
                       labels = axis_labels$y.label) +
    geom_path(data = court_trace, aes(x = x, y = y), color = 'black', size = 1, alpha = 0.75) +
    geom_path(data = net_trace, aes(x = x, y = y), color = 'grey40', size = 1, lineend = 'round') +
    coord_fixed()



  
```

```{r}
library(gganimate)
library(tweenr)
library(transformr)
```
#player rally animation


```{r}
p.rally.anim8 <- ggplot() + 
  scale_x_continuous(breaks = axis_labels$x.break) +
    scale_y_continuous(breaks = axis_labels$y.break) +
    geom_path(data = court_trace, aes(x = x, y = y), color = 'black', size = 1, alpha = 0.75) +
    geom_path(data = net_trace, aes(x = x, y = y), color = 'grey40', size = 1, lineend = 'round') +
    coord_fixed() +
  geom_point(data= longral_pos, aes(x=p.start.position.x, y=p.start.position.y,  group = rally.number, colour="red")) +
  geom_path(data= longral_pos, aes(x=p.start.position.x, y=p.start.position.y,  group = rally.number, alpha = shot)) +
  geom_point(data= longral_pos, aes(x=oppo.start.position.x, y=oppo.start.position.y,  group = rally.number, colour="blue")) +
  geom_path(data= longral_pos, aes(x=oppo.start.position.x, y=oppo.start.position.y,  group = rally.number, alpha = shot)) +
  geom_point(data= longral_pos, aes(x=start.x, y=start.y, group = rally.number, colour="green")) +
  transition_reveal(pos.rally.count) +
  facet_wrap(~rally.number ) +
  xlab("Player Position X ") + 
  ylab("Player Position Y") + 
  ggtitle("Animation for Federer 2016 rallies 10 shots or more")+
  scale_colour_manual(name = "", values=c("red","green","blue"), labels= c("Berdych","Ball","Federer"))

#had to reverse geom_point colour labels for some reason

animate(p.rally.anim8, duration = 30, fps = 10)
```


```{r}
p.rally.anim9 <- ggplot() + 
  scale_x_continuous(breaks = axis_labels$x.break) +
    scale_y_continuous(breaks = axis_labels$y.break) +
    geom_path(data = court_trace, aes(x = x, y = y), color = 'black', size = 1, alpha = 0.75) +
    geom_path(data = net_trace, aes(x = x, y = y), color = 'grey40', size = 1, lineend = 'round') +
    coord_fixed() +
  geom_point(data= seventythree_df, 
             aes(x=p.start.position.x, y=p.start.position.y,  group = rally.number, colour="red")) +
  geom_path(data= seventythree_df, 
            aes(x=p.start.position.x, y=p.start.position.y,  group = rally.number, alpha = shot)) +
  geom_point(data= seventythree_df, aes(x=oppo.start.position.x, y=oppo.start.position.y,  
                                        group = rally.number, colour="blue")) +
  geom_path(data= seventythree_df,aes(x=oppo.start.position.x, y=oppo.start.position.y,  
                                      group = rally.number, alpha = shot))+
  geom_point(data= seventythree_df, 
             aes(x=start.x, y=start.y, group = rally.number, colour="green")) +
  transition_reveal(pos.rally.count) +
  xlab("Player Position X ") + 
  ylab("Player Position Y") + 
  ggtitle("Federer 2016 Longest Rally Animation")+
  scale_colour_manual(name = "", values=c("red","green","blue"), labels= c("Berdych","Ball","Federer"))

#had to reverse geom_point colour labels for some reason

animate(p.rally.anim9, duration = 30, fps = 10)
```

